### ISSUE TITLE
In place variants for matrix*vector

### ISSUE THREAD

**Issue by panmari** [ungerik/go3d#10]
Heyhey

For speed reasons, it would be nice to have an in place variant for transforming a vector with a matrix, i.e.

v' = M * v

with v' directly saved into v. My proposal would be to rename the existing `MulVec3` etc. methods to `MuledVec3` and implement the in place variant under the name `MulVec3`. This breaks all code using this, though.

An alternative could be to provide the in place method under another name, e.g, `TransformVec3`.

**Comment by ungerik** [comment]
The copy of the vector is necessary anyways when you look at the algorithm.

**Comment by panmari** [comment]
Still, by writing back the result to the existing Vec3/Vec4 we don't need to allocate a new one. I put together a small [Benchmark](https://gist.github.com/panmari/a2ea60894c820f83128c). The results on my system are:
```
BenchmarkMulVec4	30000000	        35.3 ns/op
BenchmarkTransformVec4	50000000	        25.4 ns/op
```
...which would be quite significant for my application.

**Comment by ungerik** [comment]
On Thu, Jan 8, 2015 at 6:08 PM, panmari <notifications@github.com> wrote:

> BenchmarkMulVec4    30000000            35.3 ns/op
> BenchmarkTransformVec4  50000000            25.4 ns/op
>
>
This quite surprising, since copy by value assignments should be cheap and
TransformVec4 must have one in it's internal implementation. There are no
dynamic allocations.

Anyhow, I see the utility of having TransformVec4 and will implement it.

-Erik




-- 
+43 650 58 33055
erik@erikunger.com
Skype: ungerik
http://erikunger.com
http://github.com/ungerik
http://twitter.com/ungerik
http://facebook.com/ungerik
http://www.linkedin.com/in/ungerik
http://www.xing.com/profile/Erik_Unger2

**Comment by ungerik** [comment]
Did you do the internal copy in your benchmark?

-Erik

On Thu, Jan 8, 2015 at 7:44 PM, Erik Unger <erik@erikunger.com> wrote:

>
> On Thu, Jan 8, 2015 at 6:08 PM, panmari <notifications@github.com> wrote:
>
>> BenchmarkMulVec4    30000000            35.3 ns/op
>> BenchmarkTransformVec4  50000000            25.4 ns/op
>>
>>
> This quite surprising, since copy by value assignments should be cheap and
> TransformVec4 must have one in it's internal implementation. There are no
> dynamic allocations.
>
> Anyhow, I see the utility of having TransformVec4 and will implement it.
>
> -Erik
>
>
>
>
> --
> +43 650 58 33055
> erik@erikunger.com
> Skype: ungerik
> http://erikunger.com
> http://github.com/ungerik
> http://twitter.com/ungerik
> http://facebook.com/ungerik
> http://www.linkedin.com/in/ungerik
> http://www.xing.com/profile/Erik_Unger2
>



-- 
+43 650 58 33055
erik@erikunger.com
Skype: ungerik
http://erikunger.com
http://github.com/ungerik
http://twitter.com/ungerik
http://facebook.com/ungerik
http://www.linkedin.com/in/ungerik
http://www.xing.com/profile/Erik_Unger2
