### ISSUE TITLE
MulVec3 is broken

### ISSUE THREAD

**Issue by dblezek** [ungerik/go3d#12]
Hi,  This code in `float64/mat3/mat3.go` is broken:

```
func (mat *T) MulVec3(v *vec3.T) vec3.T {
return vec3.T{
mat[0][0]*v[0] + mat[1][0]*v[1] + mat[2][0]*v[2],
mat[0][1]*v[1] + mat[1][1]*v[1] + mat[2][1]*v[2],
mat[0][2]*v[2] + mat[1][2]*v[1] + mat[2][2]*v[2],
}
}
```

It should read (pay special attention to the first column):

```
func (mat *T) MulVec3(v *vec3.T) vec3.T {
return vec3.T{
mat[0][0]*v[0] + mat[1][0]*v[1] + mat[2][0]*v[2],
mat[0][1]*v[0] + mat[1][1]*v[1] + mat[2][1]*v[2],
mat[0][2]*v[0] + mat[1][2]*v[1] + mat[2][2]*v[2],
}
}
```

Looks like a cut-n-paste error, because TransformVec3 is correct.

**Comment by ungerik** [comment]
Thanks, fixed.

-Erik

On Fri, Feb 13, 2015 at 9:34 PM, Daniel Blezek <notifications@github.com>
wrote:

> Hi, This code in float64/mat3/mat3.go is broken:
>
> func (mat *T) MulVec3(v *vec3.T) vec3.T {
> return vec3.T{
> mat[0][0]*v[0] + mat[1][0]*v[1] + mat[2][0]*v[2],
> mat[0][1]*v[1] + mat[1][1]*v[1] + mat[2][1]*v[2],
> mat[0][2]*v[2] + mat[1][2]*v[1] + mat[2][2]*v[2],
> }
> }
>
> It should read:
>
> ```func (mat
>
> *T) MulVec3(v *vec3.T) vec3.T { return vec3.T{ mat[0][0]*v[0] + mat[1][0]*v[1]
> + mat[2][0]*v[2],
> mat[0][1]*v[0] + mat[1][1]*v[1] + mat[2][1]
> *v[2], mat[0][2]*v[0] + mat[1][2]*v[1] + mat[2][2]*v[2],
> }
> }
>
>
> Looks like a cut-n-paste error, because TransformVec3 is correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ungerik/go3d/issues/12>.
>



-- 
+43 650 58 33055
erik@erikunger.com
Skype: ungerik
http://erikunger.com
http://github.com/ungerik
http://twitter.com/ungerik
http://facebook.com/ungerik
http://www.linkedin.com/in/ungerik
http://www.xing.com/profile/Erik_Unger2
