### ISSUE TITLE
Rotating vector by quaternion, normalizes it

### ISSUE THREAD

**Issue by SQLek** [ungerik/go3d#20]
Rotating anything by identity shouldn't change anything.
`vec := vec3.T{1,1,1}
	fmt.Printf("%v rotating by identity gives %v\n",
		vec,quaternion.Ident.RotatedVec3(&vec))`

> [1 1 1] rotating by identity gives [0.5773503 0.5773503 0.5773503]

Quaternion rotation converts input to another quaternion and multiply it.

Normalizing quaternions is itself wise idea, but this vector normalization side-efect isn't so nice.

**Comment by ungerik** [comment]
Thanks, will have a look at it

**Comment by lotsofone** [comment]
Any update to this issue?

**Comment by ungerik** [comment]
Forgot about it. Would appreciate a PR if you have looked into it
