### ISSUE TITLE
multiplying vector by float

### ISSUE THREAD

**Issue by majimboo** [ungerik/go3d#26]
Can we add this feature to vec3? I suggest

    a := vec3.Zero
    b := 5.0
    a.MulFloat(b)

    func (vec) MulFloat(f float64) {
        vec[0] *= f
        vec[1] *= f
        vec[2] *= f

Thank you

**Comment by ungerik** [comment]
It's already implemented:
```go
func (vec *T) Scale(f float32) *T {
	vec[0] *= f
	vec[1] *= f
	vec[2] *= f

	return vec
}```
